"""diseases

Revision ID: 6a082b648dcb
Revises: 62a8f0f5c8e4
Create Date: 2024-05-30 22:58:24.461432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a082b648dcb'
down_revision = '62a8f0f5c8e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disease',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('plant_type', sa.String(length=100), nullable=False),
    sa.Column('symptoms', sa.Text(), nullable=False),
    sa.Column('causes', sa.Text(), nullable=False),
    sa.Column('treatments', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('disease')
    # ### end Alembic commands ###
