"""add timestamp

Revision ID: c33b6b1662fe
Revises: cb60df5a9219
Create Date: 2024-06-01 00:34:46.879954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c33b6b1662fe'
down_revision = 'cb60df5a9219'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
